In [ ]:
import pandas as pd
import re

# Step 1: Load dataset with correct encoding
df = pd.read_csv("C:/Users/bhumi/OneDrive/Desktop/professional/internship/Mobiles_Dataset.csv", encoding='latin1')

# Step 2: Drop exact duplicate rows
df = df.drop_duplicates()

# Step 3: Basic data inspection
print(df.head())
print(df.tail())
print(df.info())
print(df.isnull().sum())

# Step 4: Fill missing Camera values
df['Camera'] = df['Camera'].fillna('Unknown')

# Step 5: Remove non-numeric symbols (e.g., currency symbols) from price columns
df['Actual price'] = df['Actual price'].replace('[^0-9]', '', regex=True)
df['Discount price'] = df['Discount price'].replace('[^0-9]', '', regex=True)

# Step 6: Replace empty strings with NaN (if any price cells were fully non-numeric)
df['Actual price'].replace('', pd.NA, inplace=True)
df['Discount price'].replace('', pd.NA, inplace=True)

# Step 7: Drop rows with missing price values
df.dropna(subset=['Actual price', 'Discount price'], inplace=True)

# Step 8: Convert prices to integer
df['Actual price'] = df['Actual price'].astype(int)
df['Discount price'] = df['Discount price'].astype(int)

#Step 9: Normalize product names by removing color keywords from within brackets
def clean_model_name(name):
    color_words = [
        'black', 'blue', 'white', 'green', 'red', 'purple', 'grey', 'silver',
        'gold', 'pink', 'yellow', 'coral', 'midnight', 'deep', 'starlight',
        'titanium', 'graphite', 'bronze', 'orange', 'cyan'
    ]
    
    name_lower = name.lower()

    # Remove color keywords
    for color in color_words:
        pattern = rf"\b{color}\b"
        name_lower = re.sub(pattern, '', name_lower)

    # Remove extra commas/spaces inside parentheses
    name_lower = re.sub(r'\(\s*,', '(', name_lower)
    name_lower = re.sub(r',\s*\)', ')', name_lower)
    name_lower = re.sub(r'\(\s*\)', '', name_lower)

    # Remove multiple spaces and strip
    name_lower = re.sub(r'\s+', ' ', name_lower).strip()

    return name_lower.title()

# Apply model name cleaner
df['Model Name'] = df['Product Name'].apply(clean_model_name)

# Step 10: Drop duplicate models based on cleaned name
df = df.drop_duplicates(subset='Model Name', keep='first')

# Step 11: Save cleaned dataset
df.to_csv("C:/Users/bhumi/OneDrive/Desktop/professional/internship/mobile_cleaned.csv", index=False)

                         Product Name Actual price Discount price  Stars  \
0     Apple iPhone 15 (Green, 128 GB)     ??79,600       ??65,999    4.6
1      Apple iPhone 15 (Blue, 128 GB)     ??79,600       ??65,999    4.6
2     Apple iPhone 15 (Black, 128 GB)     ??79,600       ??65,999    4.6
3  OnePlus N20 SE (JADE WAVE, 128 GB)     ??19,999       ??11,489    4.0
4  OnePlus N20 SE (BLUE OASIS, 64 GB)     ??16,999       ??12,999    4.0

           Rating        Reviews RAM (GB) Storage (GB)  Display Size (inch)  \
0  44,793 Ratings  2,402 Reviews      NIL          128                 6.10
1  44,793 Ratings  2,402 Reviews      NIL          128                 6.10
2  44,793 Ratings  2,402 Reviews      NIL          128                 6.10
3   1,005 Ratings     41 Reviews        4          128                 6.56
4   1,005 Ratings     41 Reviews        4           64                 6.56

        Camera                                        Description  \
0  48MP + 12MP  128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...
1  48MP + 12MP  128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...
2  48MP + 12MP  128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...
3        50MP   4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...
4        50MP   4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...

                                                Link
0  https://www.flipkart.com/apple-iphone-15-green...
1  https://www.flipkart.com/apple-iphone-15-blue-...
2  https://www.flipkart.com/apple-iphone-15-black...
3  https://www.flipkart.com/oneplus-n20-se-jade-w...
4  https://www.flipkart.com/oneplus-n20-se-blue-o...
     Product Name Actual price Discount price  Stars          Rating  \
979  Kechaoda A27      ??1,499          ??967    4.0  11,022 Ratings
980  Kechaoda A27      ??1,499          ??975    4.0  11,022 Ratings
981  Kechaoda A27      ??1,499          ??975    4.0  11,022 Ratings
982  Kechaoda A27      ??1,499          ??930    4.0  11,022 Ratings
983  Kechaoda A27      ??1,499          ??967    4.0  11,022 Ratings

         Reviews RAM (GB) Storage (GB)  Display Size (inch)       Camera  \
979  693 Reviews      NIL          NIL                 0.66  0MP | 0MP
980  693 Reviews      NIL          NIL                 0.66          NaN
981  693 Reviews      NIL          NIL                 0.66          NaN
982  693 Reviews      NIL          NIL                 0.66  0MP | 0MP
983  693 Reviews      NIL          NIL                 0.66  0MP | 0MP

                                           Description  \
979  32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...
980  32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...
981  32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...
982  32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...
983  32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...

                                                  Link
979  https://www.flipkart.com/kechaoda-a27/p/itmfe3...
980  https://www.flipkart.com/kechaoda-a27/p/itmfe3...
981  https://www.flipkart.com/kechaoda-a27/p/itmfe3...
982  https://www.flipkart.com/kechaoda-a27/p/itmfe3...
983  https://www.flipkart.com/kechaoda-a27/p/itmfe3...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Name         984 non-null    object
 1   Actual price         984 non-null    object
 2   Discount price       984 non-null    object
 3   Stars                984 non-null    float64
 4   Rating               984 non-null    object
 5   Reviews              984 non-null    object
 6   RAM (GB)             984 non-null    object
 7   Storage (GB)         984 non-null    object
 8   Display Size (inch)  984 non-null    float64
 9   Camera               908 non-null    object
 10  Description          984 non-null    object
 11  Link                 984 non-null    object
dtypes: float64(2), object(10)
memory usage: 92.4+ KB
None
Product Name            0
Actual price            0
Discount price          0
Stars                   0
Rating                  0
Reviews                 0
RAM (GB)                0
Storage (GB)            0
Display Size (inch)     0
Camera                 76
Description             0
Link                    0
dtype: int64

C:\Users\bhumi\AppData\Local\Temp\ipykernel_2008\2920652955.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Actual price'].replace('', pd.NA, inplace=True)
C:\Users\bhumi\AppData\Local\Temp\ipykernel_2008\2920652955.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discount price'].replace('', pd.NA, inplace=True)